# Release workflow. Performs checks and releases.

name: Main branch checks, build and release process

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    environment: Semantic Release to NPM environment
    runs-on: ubuntu-latest
    permissions:
      contents: write # To publish a GitHub release.
      issues: write # To comment on released issues.
      pull-requests: write # To comment on released pull requests.
      id-token: write # To enable use of OIDC for npm provenance.
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: ./package-lock.json
      - name: Install dependencies
        run: npm clean-install
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Clean dist/
        run: npm run clean
      - name: Build
        run: npm run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
